name: Release next version to GitHub Maven Repository

on: workflow_dispatch

jobs:
  release:
    name: SBT Release
    runs-on: ubuntu-latest
    #if: ${{ github.ref == 'refs/heads/main' }}
    permissions:
      id-token: write
      pull-requests: write
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup Scala
        uses: japgolly/setup-everything-scala@v3.1
        with:
          java-version: temurin:1.23.0.1
      - name: Release new version
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.MAVEN_PUBLISH_TOKEN }}
        run: |
          git config --global user.email "delamain@esdservices.net"
          git config --global user.name "Delamain Network"
          sbt 'release with-defaults'
          
          currentVersion=$(git describe --tags --abbrev=7)
          gh release create "$currentVersion" --generate-notes
