name: Publish tagged commit to GitHub Maven Repository

on: workflow_dispatch

jobs:
  release:
    name: SBT Release
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags') }}
    permissions:
      id-token: write
      pull-requests: write
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup Scala
        uses: japgolly/setup-everything-scala@v3.1
        with:
          java-version: temurin:1.23.0.1
      - name: Release new version
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.MAVEN_PUBLISH_TOKEN }}
          IS_DEV: ${{ !startsWith(github.ref, 'refs/heads/release') }}
        run: |
          sbt 'release with-defaults'
